//
//  PairingService.swift
//  Sea you soon
//
//  Pairing-code redemption. A crew member generates a short code on Crew Deck
//  (the crew website — issuing the code IS the consent); the family redeems it
//  here.
//
//  The code carries the crew member's identity server-side — the family never
//  types an ID of any kind, and a guessed/mistyped code simply won't redeem.
//  There is no backend yet, so `MockPairingService` resolves a small set of
//  seeded codes locally. `RemotePairingService` is the real implementation,
//  ready to point at the API once it's hosted. Swap via `Pairing.service`.
//

import Foundation

// MARK: - Redemption result

/// What a valid pairing code resolves to. This drives the whole app.
/// No crew ID anywhere: accounts are username-based (see the server's db.py
/// for the threat-model reasoning).
struct CrewProfile: Codable, Equatable {
    let accountId: String       // the crew member's account username, internal
    let watchId: String         // this family link's id (for later revocation)
    let crewName: String
    let shipName: String
    let embarkDate: Date
    let disembarkDate: Date
}

// MARK: - Errors

enum PairingError: LocalizedError {
    case invalidCode
    case expired
    case alreadyRedeemed
    case network

    var errorDescription: String? {
        switch self {
        case .invalidCode:     return "That code wasn't recognised. Please check it and try again."
        case .expired:         return "That code has expired. Ask your seafarer to generate a new one."
        case .alreadyRedeemed: return "That code has already been used. Ask for a fresh code."
        case .network:         return "Couldn't reach the server. Please check your connection and try again."
        }
    }
}

// MARK: - Protocol

protocol PairingService {
    /// Redeem a pairing code on behalf of a named family member.
    /// - Returns: the crew profile the code is linked to.
    func redeem(code: String, watcherName: String) async throws -> CrewProfile
}

extension PairingService {
    /// Normalise user input: uppercase, trim, collapse spaces (keep the dash).
    func normalize(_ code: String) -> String {
        code.uppercased()
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: " ", with: "")
    }
}

/// The service the app currently uses.
/// Live backend on the VPS (Crew Deck), served at the branded domain.
enum Pairing {
    static let service: any PairingService =
        RemotePairingService(baseURL: URL(string: "https://crew.oconnell-connect.com")!)
    // Offline fallback for development without the server:
    // static let service: any PairingService = MockPairingService()
}

// MARK: - Mock (no backend required)

/// Resolves a few hard-coded codes so the flow works end-to-end offline.
/// Stands in for codes a crew member would have generated on the website.
struct MockPairingService: PairingService {
    func redeem(code: String, watcherName: String) async throws -> CrewProfile {
        try? await Task.sleep(for: .milliseconds(600))   // feel like a network call

        let normalized = normalize(code)
        guard let seed = Self.seededCodes[normalized] else {
            throw PairingError.invalidCode
        }
        return CrewProfile(
            accountId: seed.accountId,
            watchId: UUID().uuidString,
            crewName: seed.crewName,
            shipName: seed.shipName,
            embarkDate: Self.date(seed.embark),
            disembarkDate: Self.date(seed.disembark)
        )
    }

    struct Seed {
        let accountId, crewName, shipName: String
        let embark, disembark: (Int, Int, Int)   // y, m, d
    }

    /// Demo codes (as if already generated by crew). Dates overlap the bundled
    /// Fleet_en.json so "today" shows a live position.
    static let seededCodes: [String: Seed] = [
        "SOL-7X4K9": Seed(accountId: "patrick.sol", crewName: "Patrick",
                          shipName: "AIDAsol", embark: (2026, 7, 13), disembark: (2026, 11, 15)),
        "NOVA-3M8Q2": Seed(accountId: "jojo.nova", crewName: "Jojo",
                           shipName: "AIDAnova", embark: (2026, 7, 15), disembark: (2027, 5, 15)),
    ]

    private static func date(_ ymd: (Int, Int, Int)) -> Date {
        var c = DateComponents()
        (c.year, c.month, c.day) = ymd
        return Calendar(identifier: .gregorian).date(from: c) ?? .now
    }
}

// MARK: - Remote (real API — ready for when the backend exists)

/// POSTs to the pairing API. Not used until `Pairing.service` points at it.
struct RemotePairingService: PairingService {
    var baseURL: URL

    func redeem(code: String, watcherName: String) async throws -> CrewProfile {
        let url = baseURL.appendingPathComponent("pairing-codes/redeem")
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try JSONEncoder().encode(
            ["code": normalize(code), "watcherName": watcherName]
        )

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await URLSession.shared.data(for: request)
        } catch {
            throw PairingError.network
        }

        switch (response as? HTTPURLResponse)?.statusCode {
        case 200:
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            do { return try decoder.decode(CrewProfile.self, from: data) }
            catch { throw PairingError.network }
        case 404: throw PairingError.invalidCode
        case 410: throw PairingError.expired
        case 409: throw PairingError.alreadyRedeemed
        default:  throw PairingError.network
        }
    }
}
